<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NDATSTNPC074" name="com.markit.common.framework.runtestsuit.RunTestSuit" tests="9" failures="0" timestamp="16 Jun 2016 12:16:25 GMT" time="692.126" errors="1">
  <testcase name="verifyKycMcpmLogin_UAT" time="122.309" classname="com.markit.common.framework.runtestsuit.RunTestSuit"/>
  <testcase name="verifyKycMcpmLogin_QA" time="107.084" classname="com.markit.common.framework.runtestsuit.RunTestSuit"/>
  <testcase name="verifySPLogin_QA" time="34.051" classname="com.markit.common.framework.runtestsuit.RunTestSuit"/>
  <testcase name="verifySPLogin_UAT" time="34.025" classname="com.markit.common.framework.runtestsuit.RunTestSuit"/>
  <testcase name="verifyPegaLogin_Prod" time="148.292" classname="com.markit.common.framework.runtestsuit.RunTestSuit">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.markit.common.framework.util.WebUtil.verifyElementDisplayed(WebUtil.java:1054)
	at com.markit.common.framework.runtestsuit.RunTestSuit.verifyPegaLogin_Prod(RunTestSuit.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- verifyPegaLogin_Prod -->
  <testcase name="verifySPLogin_Prod" time="37.766" classname="com.markit.common.framework.runtestsuit.RunTestSuit"/>
  <testcase name="verifyPegaLogin_UAT" time="45.198" classname="com.markit.common.framework.runtestsuit.RunTestSuit"/>
  <testcase name="verifyKycMcpmLogin_Prod" time="131.235" classname="com.markit.common.framework.runtestsuit.RunTestSuit"/>
  <testcase name="verifyPegaLogin_QA" time="32.166" classname="com.markit.common.framework.runtestsuit.RunTestSuit"/>
</testsuite> <!-- com.markit.common.framework.runtestsuit.RunTestSuit -->
